config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :home, only: %i[index]
  resources :groups, only: %i[index show new create] do |r|
    resources :expenses, only: %i[index new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/expenses_group.rb
class ExpensesGroup < ApplicationRecord
  belongs_to :group
  belongs_to :expense

  validates :expense_id, uniqueness: { scope: :group_id }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy
  has_many :expenses, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @expenses = @group.expenses.order(created_at: :desc)
    @total_amount = @expenses.sum(:amount)
  end

  def new
    @expense = Expense.new
    @groups = current_user.groups.includes(:expenses)
  end

  def create
    @new_expense = Expense.new(expense_params)
    if @new_expense.group_ids.empty?
      flash[:error] = 'At one least category must be selected'
      redirect_to new_group_expense_path(group_id: params[:group_id])
    else
      @expense = Expense.new(name: @new_expense.name, amount: @new_expense.amount)
      @expense.user = current_user
      @new_expense.group_ids.each do |group_id|
        @group = current_user.groups.find(group_id)
        @group.expenses << @expense
      end
      @group = Group.find(params[:group_id])
      if @expense.save
        redirect_to group_path(@group)
      else
        @groups = current_user.groups
        render :new
      end
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups.includes(:expenses)
  end

  def show
    @group = current_user.groups.find(params[:id])
    @expenses = @group.expenses.order(created_at: :desc)
    @total_amount = @expenses.sum(:amount)
  end

  def expenses; end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    redirect_to groups_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/group_expenses_helper.rb
module GroupExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/_partials/_header.html.erb
<nav class="navbar mobile-header">
  <%= link_to back_path, class: "back-button" do%>
    <span><i class="fa fa-arrow-left" style="color: white; font-size: 1.5rem"></i></span>
  <% end %>
  <h3 class="header-title"><%= title.upcase %></h3>
  <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-danger" do%>
    <span>Log out</span>
    <i class="fa fa-sign-out"></i>
  <%end%>
</nav>

app/views/expenses/new.html.erb
<%= render partial: "_partials/header", locals: { title: "New Transaction", back_path: group_path(id: params[:group_id])} %>
<div class='container d-flex justify-content-center align-items-center' style="height: 88vh">
  <div class="form">
    <%= form_with(model: @expense, url: group_expenses_path, method: :post, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control", required: true %>
      </div>
      <div class="form-group">
        <%= form.label :amount %>
        <%= form.number_field :amount, class: "form-control", required: true, step: "0.01" %>
      </div>
      <div class="d-flex align-items-center">
        <div class="d-flex flex-column" style="width: 30%; height: 30vh; overflow-y: scroll">
          <%= form.label :group_ids, "Select categories" %>
          <%= form.collection_check_boxes :group_ids, @groups, :id, :name %>
        </div>
        <% if flash[:error] %>
          <span class="alert alert-danger container" style="height: fit-content; width: fit-content"><%= flash[:error] %></span>
        <% end %>
      </div>
      <%= form.submit "SAVE", class: "btn btn-add", style: "margin-top: 8rem" %>
    <% end %>
  </div>
</div>

app/views/groups/_expense.html.erb
<div class="card expenses-container p-2">
  <div class="g-0 d-flex align-items-center justify-content-between p-2">
    <div class="d-flex flex-column gap-2 align-items-start">
      <div class="d-flex">
        <h3 class="expenses-detail">Transaction N°<%= expense.id%></h3>
        <h4 class="expenses-body"><%= expense.name %></h5>
      </div>
      <div>
        <span class="category-date"><%= expense.created_at.strftime("%d %b %Y")%></span>
      </div>
    </div>
    <div class="">
      <h5 class="expenses-amount"><%= number_to_currency(expense.amount) %></h4>
    </div>
  </div>
</div>

app/views/groups/_group.html.erb
<div class="card m-3">
  <div class="g-0 category-card">
    <div class="d-flex align-items-center">
      <div class="">
        <%= image_tag(group.icon, alt: "category icon", class: "category-icon") %>
      </div>
      <div class="mx-3">
        <div class="card-body">
          <h5 class="card-title fw-bold"><%= group.name %></h5>
        </div>
        <span class="category-date"><%= group.created_at.strftime("%d %b %Y")%></span>
      </div>
    </div>
    <div class="">
      <h4 class="category-total"><%= number_to_currency(group.expenses.sum(:amount)) %></h4>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="catgories-container d-flex flex-column">
  <%= render partial: "_partials/header", locals: { title: "Categories", back_path: root_path} %>
  <div class="category-cards text-center">
    <%if @groups.empty? %>
    <h2 class="fw-bold mt-5 display-3">There is no category</h2>
    <p class="mt-3 display-7">Try to add one with the below button</p>
    <%else%>
      <% @groups.each do |group|%>
        <%= link_to group_path(group), style: "text-decoration: none" do%>
          <%= render partial: "group", locals: { group: group } %>
        <%end%>
      <%end%>
    <%end%>
  </div>
  <%= link_to new_group_path, class: "btn btn-add", style: "margin: auto" do %>
    <span>
      ADD A NEW CATEGORY
    </span>
  <% end %>
</div>

app/views/groups/new.html.erb
<%= render partial: "_partials/header", locals: { title: "New Categories", back_path: root_path} %>
<div class='container d-flex justify-content-center align-items-center' style="height: 90vh">
  <div class="form">
    <%= form_with model: @group, url: groups_path do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control", placeholder: "Name of a new category" %>
      </div>
      <div class="form-group">
        <%= form.label :icon, "Enter URL to Icon" %>
        <%= form.text_field :icon, class: "form-control", placeholder: "e.g. 'https://picsum.photos/70/70'" %>
      </div>
      <%= form.submit "SAVE", class: "btn btn-add", style: "margin-top: 15rem" %>
    <% end %>
  </div>
<div>

app/views/groups/show.html.erb
<div>
  <%= render partial: "_partials/header", locals: { title: "Your Transactions", back_path: groups_path} %>

  <div class="card w-100 mt-1">
    <div class="g-0 d-flex align-items-center p-2 justify-content-between">
      <div class="">
        <div class="card-body">
          <h5 class="display-6 fw-bold text-center" style="color: rgb(156, 154, 154)"><%= @group.name %></h5>
        </div>
      </div>
      <div class="">
        <h4 class="fw-bold" style="color: rgb(156, 154, 154)"><%= number_to_currency(@group.expenses.sum(:amount)) %></h4>
      </div>
    </div>
  </div>

  <div class="text-center expenses-main-container p-2">
    <%if @expenses.empty? %>
    <h2 class="fw-bold mt-5 display-6">There Is No Transactions</h2>
    <p class="mt-3 display-7">Try to add one with the below button</p>
    <%else%>
      <% @expenses.each do |expense|%>
          <%= render partial: "expense", locals: { expense: expense } %>
      <%end%>
    <%end%>
  </div>
  <%= link_to new_group_expense_path(@group), class: "btn btn-add", style: "margin: auto" do %>
    <span>
      ADD A NEW TRANSACTION
    </span>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="app-name">
  <span>T</span>
  <span>r</span>
  <span>a</span>
  <span>n</span>
  <span>s</span>
  <span>a</span>
  <span>c</span>
  <span>t</span>
  <span>i</span>
  <span>o</span>
  <span>n</span>
  <span>&nbsp;</span>
  <span>T</span>
  <span>r</span>
  <span>o</span>
  <span>v</span>
  <span>e</span>
</div>
<div class="splash-bg shadow-1-strong rounded d-flex flex-column justify-content-center align-items-center">
  <div class="sign_in_container text-center">
    <%= link_to 'LOG IN', new_user_session_path, class: "btn btn-primary mb-4 py-3" %>
    <%= link_to 'SIGN UP', new_user_registration_path, class: "btn btn-secondary mb-2 py-3" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Transaction Trove</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class=''>
      <div>
        <%= yield %>
      </div>
    </div>
    <% if flash[:notice] %>
      <div class="alert alert-success container"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger container"><%= flash[:alert] %></div>
    <% end %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNSbNt0" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>